# Training

defaults:
  - config

hydra:
  run:
    dir: E:\yyb\cliport-master\cliport # ${train.train_dir}

dataset:
  type: 'single' # 'single' or 'multi'
  images: True
  cache: True  # load episodes to memory instead of reading from disk
  augment:
    theta_sigma: 60 # rotation sigma in degrees; N(mu = 0, sigma = theta_sigma).

train:
  # folders
  exp_folder: exps
  train_dir: E:\yyb\cliport-master\data\packing-boxes-pairs-seen-colors-train # assembling-kits-seq-full-train #  # ${root_dir}/${train.exp_folder}/${train.task}-${train.agent}-n${train.n_demos}-train
  data_dir: E:\yyb\cliport-master\data # ${root_dir}/data

  # task configs
  task:  packing-boxes-pairs-seen-colors # packing-boxes-pairs-seen-colors
  agent: cliport # two_stream_full_clip_lingunet_lat_transporter
  n_demos: 100
  n_steps: 20000  # 201000# use 601000 for multi-task models

  # hyper params
  n_rotations: 36
  batchnorm: False # important: False because batch_size=1
  lr: 1e-4

  attn_stream_fusion_type: 'add'
  trans_stream_fusion_type: 'conv'
  lang_fusion_type: 'mult'

  # script configs
  gpu: [0] # [0] # -1 for all
  log: False # log metrics and stats to wandb
  n_val: 10
  val_repeats: 1
  save_steps: [1000, 2000, 3000, 4000, 5000, 7000, 10000, 20000, 40000, 80000, 120000, 160000, 200000, 300000, 400000, 500000, 600000, 800000, 1000000, 1200000]
  load_from_last_ckpt: True

wandb:
  run_name: 'cliport0'
  logger:
    entity: cliport
    project: cliport
    tags: []
    group: train
    offline: False
  saver:
    upload: False
    monitor: 'val_loss'